apiVersion: apps/v1
kind: Deployment
metadata:
  name: dental-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dental-frontend
  template:
    metadata:
      labels:
        app: dental-frontend
    spec:
      containers:
        - name: dental-frontend
          image: <replace-at-runtime-in-GitHub-Actions>
          ports:
            - containerPort: 80
