apiVersion: v1
kind: Service
metadata:
  name: dental-frontend-service
spec:
  type: LoadBalancer
  selector:
    app: dental-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
