name: Deploy Frontend to EKS

on:
  push:
    branches: [master]

jobs:
  deploy:
    name: Build, Test, and Deploy Frontend
    runs-on: ubuntu-latest

    env:
      AWS_REGION: ${{ secrets.AWS_REGION }}
      ECR_REGISTRY: 736744502716.dkr.ecr.us-east-1.amazonaws.com
      ECR_REPOSITORY: my-dental-app-frontend
      IMAGE_TAG: ${{ github.sha }}

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      # Configure AWS credentials using GitHub Secrets
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Log in to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-docker-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-docker-

      # Build, tag, and push Docker image
      - name: Build, tag, and push Docker image
        env:
          AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          ECR_REPO: ${{ secrets.ECR_REPOSITORY }}
        run: |
          REPOSITORY_URI=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPO
          IMAGE_URI=$REPOSITORY_URI:${{ github.sha }}

          docker build -t $IMAGE_URI .
          docker push $IMAGE_URI

          # Inject the built image into the deployment.yaml
          sed "s|<replace-at-runtime-in-GitHub-Actions>|$IMAGE_URI|g" k8s/deployment.yaml > k8s/deployment.generated.yaml

      # Update kubeconfig
      - name: Update kubeconfig for EKS
        run: aws eks update-kubeconfig --name ${{ secrets.CLUSTER_NAME }} --region ${{ secrets.AWS_REGION }}

      # Deploy to EKS
      - name: Apply Kubernetes manifests
        run: |
          kubectl apply -f k8s/deployment.generated.yaml
          kubectl apply -f k8s/service.yaml
